spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: -1

  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: 3600
  thymeleaf:
    cache: false
  application:
    name: donuts
server:
  address: 0.0.0.0
  servlet:
    context-path: /
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  port: 8080
  tomcat:
    redirect-context-root: false
    accesslog.encoding: UTF-8


spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.url: jdbc:mysql://127.0.0.1:3306/donuts?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username: root
spring.datasource.password: 123456

mybatis-plus.configuration.log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
mybatis-plus.configuration.map-underscore-to-camel-case: true
mybatis-plus.mapper-locations: classpath:/mappers/**/*.xml



logging:
  level:
    net.wchar.donuts.mapper: debug


#防盗链
referrer.domain: localhost,127.0.0.1

#白名单
wl.list: /login.action,/captcha.action,/error

#http://127.0.0.1:8088/cas/swagger-ui/index.html
springdoc:
  swagger-ui:
    enabled: true

#http://127.0.0.1:8088/cas/doc.html
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-dynamic-parameter: true


#文件上传目录
file.upload.dir: "E:\\upload"